### ISSUE TITLE
Missing SSL certificate 

### ISSUE THREAD

**Issue by BGMP** [MaripossaGC/MaripossaGC.github.io#6]
Website has no certificate, and even though it's not handling user's input, it looks odd and, to my eyes, it should be fixed asap.

![Capture](https://user-images.githubusercontent.com/26081543/70858933-cafccd80-1ee9-11ea-87aa-b3847b792513.PNG)

Pretty sure the website used to have one. Maybe with the domain re-direction something broke and it's stopped working since? Must be related to #3

**Comment by vYuri** [comment]
SSL Certificate has been added. Yeah, it broke with the domain re-direction. Thank you 🥇
